import { useState, useEffect } from 'react';
import Head from 'next/head'
import { motion } from 'framer-motion'
// components
import Navbar from '../components/Navbar'
import Container from '../components/Container'

//------------------------------------------------------

export default function Home() {
  const [currentTheme, setCurrentTheme] = useState('dark');

  return (
    <motion.div className=' flex flex-col px-5 lg:px-0 max-w-[900px] mx-auto'>
      <Head>
        <title>Emad Code | Front end Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/webicon.svg" />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;600;700;800&display=swap'
          rel='stylesheet'
        />
      </Head>
      {/* Navbar */}
      <nav>
        <Navbar handleCurrentTheme={setCurrentTheme} />
      </nav>

      {/* Container */}
      <main>
        <Container currentTheme={currentTheme} />
      </main>
    </motion.div >
  )
}
