import Head from 'next/head'

export default function Home() {
  return (
    <div className='flex flex-col max-w-[900px] mx-auto border'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class=''>
          <h1 class="text-3xl font-bold">
            Hello world!
          </h1>
        </div>
      </main>
    </div >
  )
}
